name: librocketchatrestapi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

# don't publish it
publish_to: 'none'

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.2.1
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
